modelcontextprotocol/java-sdk

- README.md
- Add Spring AI MCP documentation section with links to client/server starters
- Fix license link text
> docs: add Spring AI MCP documentation and improve README clarity

- mcp-spring/mcp-spring-webmvc/src/main/java/io/modelcontextprotocol/server/transport/WebMvcSseServerTransport.java
Base on: https://github.com/spring-projects/spring-ai/issues/2267
The SSE connection will automatically disconnect 30 seconds after being established.
```
2025-02-24 18:13:39.403 [http-nio-8822-exec-2] INFO  i.m.server.McpAsyncServer - Client initialize request - Protocol: 2024-11-05, Capabilities: ClientCapabilities[experimental=null, roots=null, sampling=null], Info: Implementation[name=Spring AI MCP Client, version=1.0.0]
2025-02-24 18:14:09.564 [http-nio-8822-exec-5] WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver - Ignoring exception, response committed already: org.springframework.web.context.request.async.AsyncRequestTimeoutException
2025-02-24 18:14:09.564 [http-nio-8822-exec-5] WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver - Resolved …
```
> Fix issue, SSE connection will terminate after 30 seconds (DEFAULT).

- mcp-spring/mcp-spring-webmvc/src/main/java/io/modelcontextprotocol/server/transport/WebMvcSseServerTransport.java
Remove a session from the session list in `WebMvcSseServerTransport` when it times out or closes.
This is related to: https://github.com/spring-projects/spring-ai/issues/2267
When a client closes its connection then the session is still kept in the list of sessions. The transport then tries to broadcast messages to the outdated sessions and it fails with exception:
```sh
Failed to send message to session 6b973076-58fe-4613-95ba-3f39440f6ed0: Cannot invoke "org.apache.catalina.connector.OutputBuffer.isBlocking()" because "this.ob" is null
```
Unfortunately the active sessions can't be retrieved from within a test, so manual testing was done.
I created a client - server application where 100 clients connect to a server and close their connection after doing a tool request.
```sh …
```
> Remove closed sessions from list in WebMvcSseServerTransport

- mcp-spring/mcp-spring-webflux/src/main/java/io/modelcontextprotocol/client/transport/WebFluxSseClientTransport.java
> Fix some typos

- mcp/src/main/java/io/modelcontextprotocol/server/McpAsyncServer.java
> Resources and prompts cannot be added after server start 

- mcp/pom.xml
- pom.xml
Added OSGi metadata generation support using the bnd-maven-plugin to enable proper OSGi bundle creation. This change allows the SDK to be used in OSGi environments while maintaining compatibility with regular Java applications. The generated metadata includes:
- Proper bundle naming and versioning
- Explicit package exports with versions
- Optional dependencies for Jakarta
- Version ranges for required dependencies
- Java 17 capability requirement
- Verified MANIFEST.MF generation with Maven build
- Validated package exports and imports with correct versions
No breaking changes. This enhancement is completely backwards compatible:
- Non-OSGi users are unaffected
- Existing Maven builds continue to work as before
- No API changes or runtime behavior modifications
The implementation uses …
> Add OSGi Metadata Generation

- mcp/src/main/java/io/modelcontextprotocol/spec/McpSchema.java
- Add @JsonIgnoreProperties(ignoreUnknown = true) annotation to all record classes in McpSchema to make JSON deserialization more robust by ignoring unknown properties.
This improves compatibility with third-party implementations like Cursor that are not MCP Schema compliant.
> feat(mcp):  relax MCP Schema JSON deserialization constraints

- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/client/WebFluxSseMcpAsyncClientTests.java
- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/client/WebFluxSseMcpSyncClientTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/client/AbstractMcpAsyncClientTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/client/AbstractMcpSyncClientTests.java
- mcp/src/main/java/io/modelcontextprotocol/client/McpAsyncClient.java
- mcp/src/test/java/io/modelcontextprotocol/client/AbstractMcpAsyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/AbstractMcpSyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/ServletSseMcpAsyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/ServletSseMcpSyncClientTests.java
- Add proper initialization state tracking using AtomicBoolean and Sinks
- Implement timeout handling for requests requiring initialization
- Ensure all client methods verify initialization state before proceeding
- Fix rootsListChangedNotification to check initialization state
- Improve error messages for uninitialized client operations
> feat(client): Improve initialization state handling in McpAsyncClient

- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/client/WebFluxSseMcpAsyncClientTests.java
- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/client/WebFluxSseMcpSyncClientTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/client/AbstractMcpAsyncClientTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/client/AbstractMcpSyncClientTests.java
- mcp/src/main/java/io/modelcontextprotocol/client/McpAsyncClient.java
- mcp/src/main/java/io/modelcontextprotocol/client/McpClient.java
- mcp/src/main/java/io/modelcontextprotocol/client/McpSyncClient.java
- mcp/src/test/java/io/modelcontextprotocol/client/AbstractMcpAsyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/AbstractMcpSyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/HttpSseMcpAsyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/HttpSseMcpSyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/StdioMcpAsyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/StdioMcpSyncClientTests.java
- Add configurable initialization timeout separate from request timeout
- Rename ServletSse* test classes to HttpSse* for better naming consistency
- Replace direct .block() calls with StepVerifier for better reactive testing
- Improve error handling and reactive programming patterns throughout tests
- Chain reactive operations for cleaner test flow
> refactor: improve MCP client timeout handling and reactive testing

- mcp-test/src/main/java/io/modelcontextprotocol/client/AbstractMcpAsyncClientTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/client/AbstractMcpSyncClientTests.java
- mcp/src/main/java/io/modelcontextprotocol/client/transport/StdioClientTransport.java
- mcp/src/main/java/io/modelcontextprotocol/spec/DefaultMcpSession.java
- mcp/src/test/java/io/modelcontextprotocol/client/AbstractMcpAsyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/AbstractMcpSyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/StdioMcpSyncClientTests.java
This change uses `VirtualTimeScheduler` and pretends enough time has passed to trigger a timeout on the initialization.
Another problem with reliability of the tests was that the used testcontainer for the SSE server does not support multiple clients and the existence of both the global client for the entire suite and some customized local clients in some tests caused responses to be delivered to the other client at some racing situations. Now each test creates a dedicated client and performs cleanup locally.
While these tests were improved, two other issues were found and fixed:
* The first one is that the `closeGracefully` of `DefaultMcpSession` was not lazy and would trigger connection disposal before the returned `Mono` was subscribed. 
* The second one was dealing with closing the …
> Improve client test reliability and execution time

- mcp-test/src/main/java/io/modelcontextprotocol/client/AbstractMcpAsyncClientTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/client/AbstractMcpSyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/AbstractMcpAsyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/AbstractMcpSyncClientTests.java
Following #52, this PR fixes a missed duplicated connection to the testcontainer mcp server and also improves the documentation about blocking operations timing out using `VirtualTimeScheduler`.
> Follow-up fix client tests reliability

- mcp/src/main/java/io/modelcontextprotocol/spec/McpSchema.java
[MCP specification](https://github.com/modelcontextprotocol/specification/blob/bb8f4b7323693910328f72f244352cd71a0689e6/schema/draft/schema.json#L389-L391) defines `includeContext` enum values as `none`, `allServers` and `thisServer`, while `java-sdk` used `none`, `all_server` and `this_server`. This mismatch caused tool calls with sampling (e.g. [server-everything's `sampleLLM`](https://github.com/modelcontextprotocol/servers/blob/main/src/everything/everything.ts#L135)) to fail with:
````
; Execution error (McpError) at io.modelcontextprotocol.spec.DefaultMcpSession/lambda$sendRequest$12 (DefaultMcpSession.java:241).
; MCP error -32603: Cannot deserialize value of type `io.modelcontextprotocol.spec.McpSchema$CreateMessageRequest$ContextInclusionStrategy` from String "thisServer": not …
```
> Fix CreateMessageRequest includeContext enum values to match MCP specification

- mcp/src/main/java/io/modelcontextprotocol/spec/McpSchema.java
- mcp/src/test/java/io/modelcontextprotocol/spec/McpSchemaTests.java
Change format from snake_case to camelCase:
- end_turn → endTurn
- stop_sequence → stopSequence
- max_tokens → maxTokens
> refactor(McpSchema): convert StopReason enum values to camelCase

- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/WebFluxSseIntegrationTests.java
- mcp-spring/mcp-spring-webmvc/src/test/java/io/modelcontextprotocol/server/WebMvcSseIntegrationTests.java
- mcp/src/main/java/io/modelcontextprotocol/spec/McpSchema.java
- mcp/src/test/java/io/modelcontextprotocol/server/transport/HttpServletSseServerTransportProviderIntegrationTests.java
- mcp/src/test/java/io/modelcontextprotocol/spec/McpSchemaTests.java
- Implements a builder pattern for CreateMessageRequest
- Updates corresponding tests to use the new builder syntax
> feat(mcp): Add builder for CreateMessageRequest

- pom.xml
Set autoPublish to true in the Maven configuration to automatically publish artifacts to the Central repository when the release is performed.
> (pom) Enable automatic publishing to Maven Central

- mcp/src/main/java/io/modelcontextprotocol/server/transport/StdioServerTransportProvider.java
Extract message processing initialization from StdioMcpSessionTransport constructor into a separate initProcessing() method.
> refactor(server): Fi StdioServerTransportProvider initialization flow

- mcp/src/test/java/io/modelcontextprotocol/client/StdioMcpAsyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/StdioMcpSyncClientTests.java
Fixed an exception when I was performing unit testing with `./mvnw test` on a Windows system:
``` java
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.RuntimeException: Failed to start process with command: [npx, -y, @modelcontextprotocol/server-everything, dir]
Caused by: java.lang.RuntimeException: Failed to start process with command: [npx, -y, @modelcontextprotocol/server-everything, dir]
at io.modelcontextprotocol.client.transport.StdioClientTransport.lambda$connect$1(StdioClientTransport.java:132)
at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:73)
at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:32)
at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:228)
at …
```
> fix(tests): Failed to start process with command npx on Windows

- mcp/src/main/java/io/modelcontextprotocol/server/McpAsyncServer.java
- mcp/src/main/java/io/modelcontextprotocol/server/McpServer.java
- mcp/src/main/java/io/modelcontextprotocol/server/McpServerFeatures.java
Fix #98 , we need to provide a method to set server `instructions`, which needs to be the same as the [python sdk](https://github.com/modelcontextprotocol/python-sdk)
Already tested on `sync` and `async` server: 
```java
McpSyncServer server = McpServer.sync(transport)
.serverInfo("stdio-server-example", "1.0.0")
.instructions("This is a simple MCP server example that provides two tools: xxxx.")
.tool(xxx)
.build();
```
The server can return `instructions` normally: 
> 20:53:05.009 [pool-1-thread-1] INFO  i.m.client.McpAsyncClient - Server response with Protocol: 2024-11-05, Capabilities: ServerCapabilities[experimental=null, logging=LoggingCapabilities[], prompts=null, resources=null, tools=ToolCapabilities[listChanged=false]], Info: Implementation[name=stdio-server-async-example, …
> fix: add support to set server instructions

- mcp/src/main/java/io/modelcontextprotocol/server/transport/HttpServletSseServerTransportProvider.java
- mcp/src/test/java/io/modelcontextprotocol/server/transport/HttpServletSseServerCustomContextPathTests.java
- mcp/src/test/java/io/modelcontextprotocol/server/transport/HttpServletSseServerTransportProviderIntegrationTests.java
- mcp/src/test/java/io/modelcontextprotocol/server/transport/TomcatTestUtil.java
Enhance HttpServletSseServerTransportProvider to support deployment under non-root context paths by:
- Adding baseUrl field and DEFAULT_BASE_URL constant
- Creating new constructor that accepts a baseUrl parameter
- Extending Builder with baseUrl configuration method
- Prepending baseUrl to message endpoint in SSE events
- Add HttpServletSseServerCustomContextPathTests to verify custom context path functionality
- Extract common Tomcat server setup code to TomcatTestUtil for test reuse
Related to #79
> feat(mcp): Custom context paths in HTTP Servlet SSE server transport

- mcp-spring/mcp-spring-webflux/src/main/java/io/modelcontextprotocol/server/transport/WebFluxSseServerTransportProvider.java
Add error handling to return a 404 NOT_FOUND response when a request is made with a non-existent session ID. This prevents potential NullPointerExceptions when processing requests with invalid session IDs.
> fix: Add null check for session in WebFluxSseServerTransportProvider

- mcp/src/main/java/io/modelcontextprotocol/client/McpAsyncClient.java
- mcp/src/main/java/io/modelcontextprotocol/client/McpSyncClient.java
Enable the MCP Client to read the Server instructions.
The instructions are optional and exist in the MCP spec, but not fully exposed in the Java SDK yet.
Also made modifications to Spring AI and a test project that uses this.
No.
> add access to server instructions

- mcp/src/main/java/io/modelcontextprotocol/spec/McpSchema.java
```ts
/**
* The server's response to a completion/complete request */ export
interface CompleteResult extends Result {
completion: {
/**
*
An array of completion values. Must not exceed 100 items.
*/
values: string[];
/**
* The total number of completion options available. This can exceed the number of values actually sent in the response.
*/
total?: number;
/**
* Indicates whether there are additional completion options beyond those provided in the current response, even if the exact total is unknown.
*/
hasMore?: boolean;
};
}
```
> feat(completion): fix the schema about CompleteResult

- mcp/src/main/java/io/modelcontextprotocol/spec/McpClientSession.java
- mcp/src/main/java/io/modelcontextprotocol/spec/McpServerSession.java
The server originally did not support the `root/list` method, and the "method not found" error message is invalid.
> Fix method not found error msg for server

- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/WebFluxSseIntegrationTests.java
- mcp/src/main/java/io/modelcontextprotocol/server/McpAsyncServer.java
- mcp/src/main/java/io/modelcontextprotocol/server/McpServer.java
- mcp/src/main/java/io/modelcontextprotocol/util/DeafaultMcpUriTemplateManagerFactory.java
- mcp/src/main/java/io/modelcontextprotocol/util/DefaultMcpUriTemplateManager.java
- mcp/src/main/java/io/modelcontextprotocol/util/McpUriTemplateManager.java
- mcp/src/main/java/io/modelcontextprotocol/util/McpUriTemplateManagerFactory.java
- mcp/src/test/java/io/modelcontextprotocol/McpUriTemplateManagerTests.java
Implement URI template functionality for MCP resources, allowing dynamic resource URIs with variables in the format {variableName}.
- Enable resource URIs with variable placeholders (e.g., "/api/users/{userId}")
- Automatic extraction of variable values from request URIs
- Validation of template arguments in completions
- Matching of request URIs against templates
- Add new URI template management interfaces and implementations
- Enhanced resource template listing to include templated resources
- Updated resource request handling to support template matching
- Test coverage for URI template functionality
> feat: Add URI template support for MCP resources

- mcp/src/main/java/io/modelcontextprotocol/server/McpAsyncServer.java
In [0.8.0](https://github.com/modelcontextprotocol/java-sdk/releases/tag/v0.8.0) we introduced the exchange concept and required temporary existence of a dual stack API - prior one without the exchange in server features and the new one that has it. Since then we removed the deprecated functionality but we left the temporary `McpAsyncServer.AsyncServerImpl` delegate used by `McpAsyncServer`. This PR removes this temporary code.
> Remove temporary delegate impl from McpAsyncServer

- mcp/src/test/java/io/modelcontextprotocol/client/StdioMcpAsyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/StdioMcpSyncClientTests.java
The Stdio test started to fail due to a change in the server-everything running in Docker.
> Fix stdio tests - proper server-everything argument

- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/WebFluxSseIntegrationTests.java
The `WebFluxSseIntegrationTests.testLoggingNotification` test is flaky and can fail with:
```
Expected size: 3 but was: 2 in:
[LoggingMessageNotification[level=NOTICE, logger=test-logger, data=Notice message],
LoggingMessageNotification[level=ERROR, logger=test-logger, data=Another error message]]
```
When running this test in the IDE with 100 times (with 2 test params it means 200 runs) repeat mode, it can take **25s** in the optimistic variant on my machine and occasionally fails for the JDK HttpClient variant.
With this change, repeating 100 times finishes in **4s**. It essentially avoids using awaitility and instead relies on a `CountDownLatch` to coordinate completion. The flakiness comes from the fact that the results are aggregated in an `ArrayList`, which can fail to publish the …
> Fix flaky WebFluxSse integration test

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- SECURITY.md
The contributing guidelines were inspired by the guidelines in the MCP Specification repository. The Code of Conduct and Security Guidelines are copied verbatim.
> Add Contributing Guidelines and Code of Conduct

- mcp/src/main/java/io/modelcontextprotocol/server/McpAsyncServerExchange.java
- mcp/src/main/java/io/modelcontextprotocol/server/McpSyncServerExchange.java
Fixes the Javadoc comments on `loggingNotification` in the exchange classes to specify that only the client on the exchange will receive the notification.
The `loggingNotification` methods on the exchange classes incorrectly state that notifications are sent to all clients, which is only the case for the deprecated methods on the server instances.
N/A
N/A
> docs: update loggingNotification javadoc to specify single client

- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/WebFluxSseIntegrationTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/client/AbstractMcpAsyncClientTests.java
- mcp/src/main/java/io/modelcontextprotocol/client/McpAsyncClient.java
- mcp/src/test/java/io/modelcontextprotocol/client/AbstractMcpAsyncClientTests.java
- Wrap the list responses in immutable lists.
- Add test to verify the immutable responses.
> refactor: return immutable lists from list methods

- mcp/src/main/java/io/modelcontextprotocol/server/McpServer.java
- mcp/src/main/java/io/modelcontextprotocol/server/McpServerFeatures.java
- mcp/src/main/java/io/modelcontextprotocol/server/McpSyncServer.java
- mcp/src/test/java/io/modelcontextprotocol/server/transport/HttpServletSseServerTransportProviderIntegrationTests.java
- mcp/src/test/java/io/modelcontextprotocol/server/transport/McpTestServletFilter.java
- mcp/src/test/java/io/modelcontextprotocol/server/transport/TomcatTestUtil.java
Add the ability to decide whether or not to use blocking code offloading in `McpSyncServer`. Turning it off allows for the propagation of `ThreadLocal`s.
I use this with Spring Security. Authentication data about the JWT that was used in the request is stored in a ThreadLocal. With `.subscribeOn(Schedulers.boundedElastic()))`, thread hops are introduced in blocking scenarios, and thread locals are lost.
In select case, when the user is sure they are NOT in a reactive context, they might want to enable "immediate execution", on the thread that calls `.block()`, for example in the `McpSyncServerExchange`, and preserve thread locals.
Trying this change with a [Spring-based sample](https://github.com/Kehrlann/spring-ai-mcp-authorization-demo), using Spring Security to pass the …
> Add option for immediate execution in McpSyncServer

- mcp/src/main/java/io/modelcontextprotocol/client/transport/HttpClientSseClientTransport.java
- mcp/src/test/java/io/modelcontextprotocol/client/transport/HttpClientSseClientTransportTests.java
- Include response body in error messages for better debugging
- Change sendHttpPost return type from HttpResponse<Void> to HttpResponse<String>
- Use BodyHandlers.ofString() instead of discarding response body
- Add testErrorOnBogusMessage test to verify error handling for invalid JSON-RPC messages
- Test validates that malformed messages return 400 status with descriptive error message
Replace #361
> fix: improve error handling in HttpClientSseClientTransport and add test

- mcp/src/main/java/io/modelcontextprotocol/server/McpAsyncServer.java
Follow up to #357 to update tool call handler signature from Map<String, Object> to McpSchema.CallToolRequest for consistency with changes in #375.
- Change BiFunction parameter from Map<String, Object> to McpSchema.CallToolRequest for better type safety
- Update method signature to accept CallToolRequest instead of raw arguments map
- Replace toolSpecification.call() with toolSpecification.callHandler()
- Migrate to builder pattern for AsyncToolSpecification construction
> refactor: Replace Map<String, Object> with CallToolRequest in StructuredOutputCallToolHandler

- mcp-spring/mcp-spring-webflux/src/main/java/io/modelcontextprotocol/server/transport/WebFluxSseServerTransportProvider.java
- mcp-spring/mcp-spring-webflux/src/main/java/io/modelcontextprotocol/server/transport/WebFluxStreamableServerTransportProvider.java
- mcp-spring/mcp-spring-webmvc/src/main/java/io/modelcontextprotocol/server/transport/WebMvcSseServerTransportProvider.java
- mcp-spring/mcp-spring-webmvc/src/main/java/io/modelcontextprotocol/server/transport/WebMvcStreamableServerTransportProvider.java
- mcp/src/main/java/io/modelcontextprotocol/client/McpAsyncClient.java
- mcp/src/main/java/io/modelcontextprotocol/server/transport/HttpServletSseServerTransportProvider.java
- mcp/src/main/java/io/modelcontextprotocol/server/transport/HttpServletStreamableServerTransportProvider.java
- mcp/src/main/java/io/modelcontextprotocol/spec/McpStreamableServerSession.java
- mcp/src/main/java/io/modelcontextprotocol/util/KeepAliveScheduler.java
- mcp/src/test/java/io/modelcontextprotocol/server/HttpServletStreamableIntegrationTests.java
- mcp/src/test/java/io/modelcontextprotocol/util/KeepAliveSchedulerTests.java
- Add KeepAliveScheduler utility class for configurable periodic session pings
- Integrate keep-alive support in WebFlux, WebMVC, and HttpServlet SSE transport providers
- Add keepAliveInterval configuration option to all transport provider builders
- Deprecate existing constructors in favor of builder pattern with enhanced configuration
- Update graceful shutdown to properly clean up keep-alive schedulers
- Add unit tests for KeepAliveScheduler functionality
- Configurable ping frequency to suit different network environments
- Optional keep-alive (disabled by default) to avoid excessive network overhead
Resolves: #414, #158
Replaces #353
This change implements the [Model Context Protocol specification recommendations for connection health …
> feat: implement MCP-compliant keep-alive functionality for server transports

- mcp/src/main/java/io/modelcontextprotocol/client/McpAsyncClient.java
- mcp/src/main/java/io/modelcontextprotocol/client/McpSyncClient.java
- Add getters for both MCP Sync/Async clients
> Expose the client initialization result

- mcp-spring/mcp-spring-webflux/src/main/java/io/modelcontextprotocol/client/transport/WebClientStreamableHttpTransport.java
- mcp-spring/mcp-spring-webflux/src/main/java/io/modelcontextprotocol/client/transport/WebFluxSseClientTransport.java
- mcp-spring/mcp-spring-webflux/src/main/java/io/modelcontextprotocol/server/transport/WebFluxSseServerTransportProvider.java
- mcp-spring/mcp-spring-webflux/src/main/java/io/modelcontextprotocol/server/transport/WebFluxStatelessServerTransport.java
- mcp-spring/mcp-spring-webflux/src/main/java/io/modelcontextprotocol/server/transport/WebFluxStreamableServerTransportProvider.java
- mcp-spring/mcp-spring-webmvc/src/main/java/io/modelcontextprotocol/server/transport/WebMvcSseServerTransportProvider.java
- mcp-spring/mcp-spring-webmvc/src/main/java/io/modelcontextprotocol/server/transport/WebMvcStreamableServerTransportProvider.java
- mcp-spring/mcp-spring-webmvc/src/test/java/io/modelcontextprotocol/server/WebMvcSseCustomContextPathTests.java
- mcp/src/main/java/io/modelcontextprotocol/client/McpAsyncClient.java
- mcp/src/main/java/io/modelcontextprotocol/client/transport/HttpClientSseClientTransport.java
- mcp/src/main/java/io/modelcontextprotocol/client/transport/HttpClientStreamableHttpTransport.java
- mcp/src/main/java/io/modelcontextprotocol/server/McpAsyncServer.java
- mcp/src/main/java/io/modelcontextprotocol/server/McpStatelessAsyncServer.java
- mcp/src/main/java/io/modelcontextprotocol/server/transport/HttpServletSseServerTransportProvider.java
- mcp/src/main/java/io/modelcontextprotocol/server/transport/HttpServletStreamableServerTransportProvider.java
- mcp/src/main/java/io/modelcontextprotocol/server/transport/StdioServerTransportProvider.java
- mcp/src/main/java/io/modelcontextprotocol/spec/HttpHeaders.java
- mcp/src/main/java/io/modelcontextprotocol/spec/McpSchema.java
- mcp/src/main/java/io/modelcontextprotocol/spec/McpServerTransportProviderBase.java
- mcp/src/main/java/io/modelcontextprotocol/spec/McpStatelessServerTransport.java
- mcp/src/main/java/io/modelcontextprotocol/spec/McpStreamableServerTransportProvider.java
- mcp/src/main/java/io/modelcontextprotocol/spec/McpTransport.java
- mcp/src/test/java/io/modelcontextprotocol/MockMcpClientTransport.java
- mcp/src/test/java/io/modelcontextprotocol/client/McpAsyncClientResponseHandlerTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/McpAsyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/McpClientProtocolVersionTests.java
- mcp/src/test/java/io/modelcontextprotocol/server/McpServerProtocolVersionTests.java
Add MCP-Protocol-Version header to all HTTP requests as required by MCP specification 2025-06-18. This enables proper server-side version negotiation and backwards compatibility handling.
- Add protocol version constants (2025-06-18 for streamable HTTP, 2024-11-05 for SSE)
- Include MCP-Protocol-Version header in all GET/POST/DELETE requests
- Update WebClientStreamableHttpTransport, WebFluxSseClientTransport, HttpClientSseClientTransport, and HttpClientStreamableHttpTransport
Complies with MCP specification requirement that HTTP clients MUST include protocol version header on all requests to MCP servers.
Related to #398 , #363 , #250
**Implementation Details:**
- Added `MCP_PROTOCOL_VERSION` and `MCP_PROTOCOL_VERSION_HEADER_NAME` constants to all HTTP transport classes
- Uses protocol …
> feat: implement MCP protocol version header support

- mcp-spring/mcp-spring-webmvc/src/main/java/io/modelcontextprotocol/server/transport/WebMvcStatelessServerTransport.java
- mcp-spring/mcp-spring-webmvc/src/test/java/io/modelcontextprotocol/server/WebMvcStatelessIntegrationTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/AbstractStatelessIntegrationTests.java
- mcp/src/main/java/io/modelcontextprotocol/server/McpStatelessServerFeatures.java
- mcp/src/main/java/io/modelcontextprotocol/server/transport/HttpServletStatelessServerTransport.java
- mcp/src/test/java/io/modelcontextprotocol/server/HttpServletStatelessIntegrationTests.java
- Add WebMvcStatelessServerTransport for mcp-spring-webmvc module
- Add HttpServletStatelessServerTransport for mcp module
- Implement builder patterns for AsyncToolSpecification and SyncToolSpecification
- Create AbstractStatelessIntegrationTests base class for shared test functionality
- Add integration tests for both transport implementations
Add WebMVC and HttpServlet stateless server transports with testing infrastructure, including builder patterns for tool specifications and shared integration test framework.
The existing codebase only had WebFlux support for stateless servers, limiting deployment options for users who prefer or require WebMVC or servlet-based solutions.
- **Integration Tests**: Both transport implementations include full integration test suites covering:
**No …
> feat: add WebMVC and HttpServlet stateless server transports

- mcp-spring/mcp-spring-webflux/src/main/java/io/modelcontextprotocol/client/transport/WebClientStreamableHttpTransport.java
- mcp-spring/mcp-spring-webflux/src/main/java/io/modelcontextprotocol/client/transport/WebFluxSseClientTransport.java
- mcp-spring/mcp-spring-webflux/src/main/java/io/modelcontextprotocol/server/transport/WebFluxSseServerTransportProvider.java
- mcp-spring/mcp-spring-webflux/src/main/java/io/modelcontextprotocol/server/transport/WebFluxStreamableServerTransportProvider.java
- mcp-spring/mcp-spring-webmvc/src/main/java/io/modelcontextprotocol/server/transport/WebMvcSseServerTransportProvider.java
- mcp-spring/mcp-spring-webmvc/src/main/java/io/modelcontextprotocol/server/transport/WebMvcStreamableServerTransportProvider.java
- mcp/src/main/java/io/modelcontextprotocol/client/LifecycleInitializer.java
- mcp/src/main/java/io/modelcontextprotocol/client/McpAsyncClient.java
- mcp/src/main/java/io/modelcontextprotocol/client/transport/HttpClientSseClientTransport.java
- mcp/src/main/java/io/modelcontextprotocol/client/transport/HttpClientStreamableHttpTransport.java
- mcp/src/main/java/io/modelcontextprotocol/server/McpAsyncServer.java
- mcp/src/main/java/io/modelcontextprotocol/server/McpStatelessAsyncServer.java
- mcp/src/main/java/io/modelcontextprotocol/server/transport/HttpServletSseServerTransportProvider.java
- mcp/src/main/java/io/modelcontextprotocol/server/transport/HttpServletStreamableServerTransportProvider.java
- mcp/src/main/java/io/modelcontextprotocol/server/transport/StdioServerTransportProvider.java
- mcp/src/main/java/io/modelcontextprotocol/spec/McpSchema.java
- mcp/src/main/java/io/modelcontextprotocol/spec/McpServerTransportProviderBase.java
- mcp/src/main/java/io/modelcontextprotocol/spec/McpStatelessServerTransport.java
- mcp/src/main/java/io/modelcontextprotocol/spec/McpTransport.java
- mcp/src/main/java/io/modelcontextprotocol/spec/ProtocolVersions.java
- mcp/src/test/java/io/modelcontextprotocol/MockMcpClientTransport.java
- mcp/src/test/java/io/modelcontextprotocol/client/McpAsyncClientResponseHandlerTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/McpAsyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/McpClientProtocolVersionTests.java
- mcp/src/test/java/io/modelcontextprotocol/server/McpServerProtocolVersionTests.java
- mcp/src/test/java/io/modelcontextprotocol/spec/McpSchemaTests.java
- Add ProtocolVersions interface with version constants
- Change protocolVersion() to protocolVersions() returning List<String>
- Streamable HTTP clients now support both 2024-11-05 and 2025-03-26
- Fixes compatibility with MCP servers that return 2024-11-05 instead of 2025-03-26
Resolves #436
Related to #438
Add multi-protocol version support to fix MCP server compatibility issues
Some MCP server implementations that support the newer "2025-03-26" protocol version incorrectly return "2024-11-05" during initialization instead. This causes compatibility issues where streamable HTTP clients (which support 2025-03-26) cannot connect to these servers because they don't advertise support for the older protocol version.
This change refactors the protocol version handling to support multiple …
> fix: add backward compatibility for MCP servers returning older protocol versions

- mcp/src/main/java/io/modelcontextprotocol/spec/HttpHeaders.java
see https://html.spec.whatwg.org/multipage/server-sent-events.html#the-last-event-id-header
> Use `Last-Event-ID` instead of `last-event-id`

- mcp/src/main/java/io/modelcontextprotocol/client/transport/HttpClientStreamableHttpTransport.java
- mcp/src/test/java/io/modelcontextprotocol/client/transport/HttpClientStreamableHttpTransportEmptyJsonResponseTest.java
- mcp/src/test/java/io/modelcontextprotocol/client/transport/HttpClientStreamableHttpTransportTest.java
> Fix httpRequestCustomizer usage in HttpClientStreamableHttpTransport

- mcp/src/main/java/io/modelcontextprotocol/client/transport/ResponseSubscribers.java
fix: https://github.com/modelcontextprotocol/java-sdk/issues/502
> fix: Fix SseLineSubscriber lacking request.

- mcp/src/main/java/io/modelcontextprotocol/client/transport/HttpClientSseClientTransport.java
When calling the MCP SSE endpoint in the current SDK, the Content-Type: application/json header is included by default. However, the SSE endpoint is accessed via a GET request, and according to HTTP specifications, the Content-Type header should not be sent with GET requests. This has caused some MCP servers to fail validation or handle the request incorrectly. Therefore, the HttpClientSseClientTransport class has been modified so that the default request builder no longer includes the Content-Type header. The Content-Type header is now only included by default for POST requests.
> fix: When call the MCP SSE endpoint, the Content-Type header not passed by default

- mcp/src/main/java/io/modelcontextprotocol/client/transport/ResponseSubscribers.java
- Add hasRequestedDemand volatile boolean flag to AggregateSubscriber and BodilessResponseLineSubscriber
- Modify hookOnSubscribe to request Long.MAX_VALUE only on first demand request
- Guard event emission in hookOnComplete with hasRequestedDemand check
- Prevents unnecessary data processing when no downstream demand exists
- Improves backpressure handling and resource efficiency
This change implements proper demand-based request handling by tracking whether demand has been requested and only emitting data when there's actual downstream demand.
The previous implementation would always emit data in `hookOnComplete()` regardless of whether there was downstream demand for it. This could lead to:
- Not Maintaining backpressure compliance
- Unnecessary data processing and memory allocation
- …
> feat: implement demand-based request handling in ResponseSubscribers

- mcp/src/main/java/io/modelcontextprotocol/server/McpStatelessServerFeatures.java
Remove LoggingCapabilities from McpStatelessServerFeatures.Async constructor as stateless servers do not support setLogging operations. This aligns the async implementation with the sync implementation which already has logging disabled.
Follows up on #463
Remove logging capabilities from stateless servers as they don't support setLogging operations.
This change fixes an inconsistency in the MCP Java SDK where stateless servers were incorrectly advertising logging capabilities. Stateless servers do not support setLogging operations, so they should not expose LoggingCapabilities in their server capabilities.
This follows up on #463 and aligns the async stateless server implementation with the sync implementation, which already correctly sets logging capabilities to null.
- Verified that …
> fix: disable logging capabilities for stateless servers

- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/client/WebClientStreamableHttpAsyncClientTests.java
- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/client/WebClientStreamableHttpSyncClientTests.java
- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/client/WebFluxSseMcpAsyncClientTests.java
- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/client/WebFluxSseMcpSyncClientTests.java
- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/client/transport/WebFluxSseClientTransportTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/client/AbstractMcpAsyncClientTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/client/AbstractMcpSyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/AbstractMcpAsyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/AbstractMcpSyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/HttpClientStreamableHttpAsyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/HttpClientStreamableHttpSyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/HttpSseMcpAsyncClientTests.java
- mcp/src/test/java/io/modelcontextprotocol/client/HttpSseMcpSyncClientTests.java
This allows reusing the containerized MCP server for all tests in a single class, significantly speeding up the tests, roughly 10x
> Use static container in all client and transport tests

- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/common/AsyncServerMcpTransportContextIntegrationTests.java
- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/common/SyncServerMcpTransportContextIntegrationTests.java
- mcp-spring/mcp-spring-webmvc/pom.xml
- mcp-spring/mcp-spring-webmvc/src/test/java/io/modelcontextprotocol/common/McpTransportContextIntegrationTests.java
- mcp/src/test/java/io/modelcontextprotocol/common/AsyncServerMcpTransportContextIntegrationTests.java
- mcp/src/test/java/io/modelcontextprotocol/common/SyncServerMcpTransportContextIntegrationTests.java
- Add integration tests for transport context propagation between MCP clients and servers
- Test both sync and async server implementations across all transport types (stateless, streamable, SSE)
- Cover Spring WebFlux and WebMVC environments with dedicated test suites
- Validate context flow through HTTP headers for authentication, correlation IDs, and metadata
- Rename existing McpTransportContextIntegrationTests to SyncServerMcpTransportContextIntegrationTests for clarity
This change adds missing test coverage for the MCP transport context feature, which allows passing contextual information (like authentication tokens, correlation IDs, or custom metadata) between MCP clients and servers through HTTP headers. The tests ensure that context propagation works correctly across:
- Different …
> test: Add additional MCP transport context integration tests

- mcp-test/src/main/java/io/modelcontextprotocol/AbstractMcpClientServerIntegrationTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/AbstractStatelessIntegrationTests.java
- mcp/src/test/java/io/modelcontextprotocol/server/AbstractMcpClientServerIntegrationTests.java
- mcp/src/test/java/io/modelcontextprotocol/server/HttpServletStatelessIntegrationTests.java
- Add try-finally blocks to guarantee server cleanup on test completion
- Call closeGracefully().block() to ensure synchronous shutdown
- Use try-with-resources for client lifecycle management where applicable
- Prevent resource leaks and potential test flakiness
> test: ensure proper resource cleanup in integration tests

- mcp-core/src/test/java/io/modelcontextprotocol/server/AbstractMcpClientServerIntegrationTests.java
- mcp-core/src/test/java/io/modelcontextprotocol/server/HttpServletSseIntegrationTests.java
- mcp-core/src/test/java/io/modelcontextprotocol/server/HttpServletStreamableIntegrationTests.java
- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/WebFluxSseIntegrationTests.java
- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/WebFluxStatelessIntegrationTests.java
- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/WebFluxStreamableIntegrationTests.java
- mcp-spring/mcp-spring-webflux/src/test/java/io/modelcontextprotocol/client/transport/WebFluxSseClientTransportTests.java
- mcp-spring/mcp-spring-webmvc/src/test/java/io/modelcontextprotocol/server/WebMcpStreamableAsyncServerTransportTests.java
- mcp-spring/mcp-spring-webmvc/src/test/java/io/modelcontextprotocol/server/WebMcpStreamableSyncServerTransportTests.java
- mcp-spring/mcp-spring-webmvc/src/test/java/io/modelcontextprotocol/server/WebMvcSseIntegrationTests.java
- mcp-spring/mcp-spring-webmvc/src/test/java/io/modelcontextprotocol/server/WebMvcStatelessIntegrationTests.java
- mcp-spring/mcp-spring-webmvc/src/test/java/io/modelcontextprotocol/server/WebMvcStreamableIntegrationTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/AbstractMcpClientServerIntegrationTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/AbstractStatelessIntegrationTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/client/AbstractMcpAsyncClientTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/server/AbstractMcpAsyncServerTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/server/AbstractMcpSyncServerTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/util/McpJsonMapperUtils.java
- mcp-test/src/main/java/io/modelcontextprotocol/util/ToolsUtils.java
- Replace @ValueSource with @MethodSource for parameterized tests
- Add clientsForTesting() methods to provide test arguments consistently
- Remove hardcoded Spring-related labels from framework-agnostic mcp-test module
- Move mcp-test's utility classes from io.modelcontextprotocol.utils to io.modelcontextprotocol.util (minor breaking change)
> refactor: standardize test parameterization and fix package naming

- mcp/pom.xml
The mcp module packages dependencies but has no sources, causing Maven release failures. Skip source and javadoc JAR generation to fix deployment errors.
> fix(mcp): skip source/javadoc generation for aggregator module

- mcp-core/src/main/java/io/modelcontextprotocol/server/McpAsyncServer.java
- mcp-core/src/main/java/io/modelcontextprotocol/server/McpStatelessAsyncServer.java
- mcp-core/src/main/java/io/modelcontextprotocol/spec/McpError.java
- mcp-core/src/main/java/io/modelcontextprotocol/spec/McpSchema.java
- mcp-core/src/test/java/io/modelcontextprotocol/spec/McpErrorTest.java
This pull-request fixes the handling of resource not found to be as described in the specification. 
see: https://modelcontextprotocol.io/specification/2025-06-18/server/resources#error-handling
Resource not found should send a JSON RPC response such as:
```json
{
"jsonrpc": "2.0",
"id": 5,
"error": {
"code": -32002,
"message": "Resource not found",
"data": {
"uri": "file:///nonexistent.txt"
}
}
}
```
I added a unit tests. 
This is not a breaking change but bug fix. 
This PR also changes some instances where a `McpError` was thrown instead of being passed in the reactive chain with `Mono.error`
> fix: handle resource not found according to spec

- mcp-core/src/main/java/io/modelcontextprotocol/server/McpAsyncServer.java
- mcp-core/src/main/java/io/modelcontextprotocol/server/McpStatelessAsyncServer.java
- mcp-core/src/main/java/io/modelcontextprotocol/server/McpStatelessSyncServer.java
- mcp-core/src/main/java/io/modelcontextprotocol/server/McpSyncServer.java
- mcp-core/src/main/java/io/modelcontextprotocol/spec/McpError.java
- mcp-core/src/main/java/io/modelcontextprotocol/spec/McpServerSession.java
- mcp-core/src/main/java/io/modelcontextprotocol/spec/McpStreamableServerSession.java
- mcp-core/src/test/java/io/modelcontextprotocol/server/AbstractMcpAsyncServerTests.java
- mcp-core/src/test/java/io/modelcontextprotocol/server/AbstractMcpClientServerIntegrationTests.java
- mcp-core/src/test/java/io/modelcontextprotocol/server/AbstractMcpSyncServerTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/AbstractMcpClientServerIntegrationTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/server/AbstractMcpAsyncServerTests.java
- mcp-test/src/main/java/io/modelcontextprotocol/server/AbstractMcpSyncServerTests.java
- Replace McpError with appropriate standard exceptions (IllegalArgumentException, IllegalStateException) for validation errors
- Change tool/prompt registration to replace existing items instead of rejecting duplicates with warningsi
- Change addTool behavior to replace existing tools instead of throwing errors
- Change addPrompt() to allow replacing existing prompts with warning instead of throwing error
- Make removal operations idempotent - log warnings instead of throwing errors for non-existent items
- Change removePrompt() to log warning instead of throwing error for non-existent prompts
- Change removeTool() to gracefully handle non-existent tools with warnings instead of errors
- Add listTools() and listPrompts() methods to all server variants (async, sync, stateless)
- Add …
> refactor: improve MCP server resilience and error handling

- mcp-core/src/main/java/io/modelcontextprotocol/client/transport/HttpClientSseClientTransport.java
- mcp-core/src/main/java/io/modelcontextprotocol/client/transport/HttpClientStreamableHttpTransport.java
- mcp-core/src/main/java/io/modelcontextprotocol/spec/HttpHeaders.java
- mcp-spring/mcp-spring-webflux/src/main/java/io/modelcontextprotocol/client/transport/WebClientStreamableHttpTransport.java
- When the client sends `notification/initalized`, servers MUST respond with HTTP 202 and an empty body. Before this PR, we checked for the absence of a Content-Type header to know whether the body was empty.
- However, some servers will send an empty body with a Content-Type header, and that header may have an unsupported, default type such as `text/html` or `text/plain`.
- Now we we also use the Content-Length header to check for an empty body. This header is optional in HTTP/2, so we do not make it our primary mechanism for detecting empty bodies.
- Fixes #582
> Client: handle server responses with Content-Length: 0

- mcp-core/src/main/java/io/modelcontextprotocol/client/transport/HttpClientStreamableHttpTransport.java
- mcp-spring/mcp-spring-webflux/src/main/java/io/modelcontextprotocol/client/transport/WebClientStreamableHttpTransport.java
Ensure warnings are logged for all non-compliant responses to JSON-RPC notifications, including empty responses. Empty responses now display as "[empty]" in log messages for better clarity.
Resolves #586
> fix: Handle non-compliant notification responses

- mcp-core/src/main/java/io/modelcontextprotocol/spec/McpSchema.java
Convert primitive int types to Integer wrapper class for:
- JSONRPCError.code
- CreateMessageRequest.maxTokens (including constructor and builder)
This allows these fields to be nullable, properly representing optional parameters in the MCP protocol schema.
> refactor: change int to Integer for optional numeric fields
